# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: kube-system
stringData:
    api-key: ENC[AES256_GCM,data:MOdHToBezlK4ZKLV+S+2raQL90KlPhvqxAhgKx697coQ5OTTaA==,iv:5rc46/UPIHz9tkPjVHUYct+3fIxhWU8JHmuamQ4h0R8=,tag:vbNSP7N9cw4fXLdAjkLkXg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y8k6aj5un65mwy7t0s6sndrpqevp3hr749facgl3ha8w5dsxqp7s95phh3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvZzM3NVpvUDNZdjJsVklL
            Vk5pRjR6WFpHWWd1ZXhxYkNSczMvRG9YbFhzCmZxRk1YT2V1QXVwdHJ0dkptWm9E
            bjNTbEZzdE1WeWhNTFhrWm9WUEY3WFUKLS0tIEIxUXZldlVwMGM5Z041TDBaRTln
            UkxnUDFYa3VJZzNJWTlKNEhQOHhDOEUKfGD3BZBn2d+zQZHSu53v+eWz36cHFMuP
            UIGHOvXzqWbL3f/Gf4UzDb8+Rohfcr8tooAL+w8yZYuS6XBy1pBiiw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-19T21:58:09Z"
    mac: ENC[AES256_GCM,data:3SiYosvphk2qGVxriKGf2/FR0v1GKkF2XcCo6jYKfLENjE2hwpvZdIWDvqf7TSVI7VxCZeIyarwPwrtM5NyGxulxhtgGx9rHIA8qNwdcT2Ar/lH1aIOBx6NlfTTt0qUwVR3yBuxpecHbAJ3Dk2nyoZEV4kan6jTyDCRnM+PeoDs=,iv:ALFIsizqI+eSDTLR+8WxVMWTvJF3gZqCBntpiD4OBso=,tag:CkivlHLBJ8Fs+ogd9tWaHw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
