# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:xbb3lLMOP6kWernnoh76IO9R,iv:ND1hGxrnBCPMGCup2MYEnftkOdcjjMRQmqLxUhhKD7U=,tag:fn1Bj2FL1hiJRjYuEigrhw==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:spECpucXojL9j64KTWOnXEShuk6Vsg6AfvPRNG/Ii4UoYqXG9w==,iv:dK8XzL1ET0pvA88wT26JAx8/ak1ZJJCLj5cK7maLH3s=,tag:NNZhZtgvIOabIbOU/uGgbQ==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:vJTcOZ1z89ZIxmqrft0=,iv:hrm7xNL+JO3mUH6kWr78VF/t+JiWcCN0pGXFRUSX/ck=,tag:oMrf+Nr5PfUOfJAAetWqUQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y8k6aj5un65mwy7t0s6sndrpqevp3hr749facgl3ha8w5dsxqp7s95phh3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByN2N6cldMRG81cWh4WldO
            dkx2RzVqallhcWhrUGEwSHRFL04rZXRFaDJVCndPb2JBTzFwZHZOc3piZnNhc0wx
            dm44b0NCOHV1anFFeFJKamtySXFRZ2sKLS0tIEhFb2pHOHZ6U1ExYmF3R3lJK0ZE
            QTByTWx1b1NMbzVZZEdzSmZMT3Y2VzQKxSm7lMpQOPCFbG+eMeVUM9bdoFuo5AlR
            ADaEXOfx6n1yZuOHFyITP7I7Fh3E41GypZoDOkw++ZrR2nXFlExB9g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-19T19:50:34Z"
    mac: ENC[AES256_GCM,data:gM/qykWcWIvcF5BrRJh1Q5SoqspGP4lqW60ljvcDB4LBnKxidkq87k2DJYd0scNM4e/IDQGirtFQXtTwJScmJc8sud/7gdHsye7F4OkiB2nc8o8LjnHsOEFA7xrSIvpjK5erRrBVs7k0+vMYyujW4JvBw8P8HKetD0zzCw++0dI=,iv:GJr93eDF74E4iHvu/Ro8Y1b4XjT0NxFh5c38sDZcLb4=,tag:EQ52HAmf7QiImQeY5sOQdA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
