# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:W6Q8HxEpa0QqYKIb8MWxoo7E,iv:2yBiYLUZFP/H8RKc/5BleK2HIvZL4rIoiNYCcmCRV0Y=,tag:bKQZNScIvoa3I+kgmVe3Rw==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data://YGvIvKTN5ASgMjXo8BGJH9gcwERfsQcoczi7rE+z+HsmNlVw==,iv:C/40Ae5P6e3GnW+/Ns2aGszwY6CHAjkV5PX8aYrKWEM=,tag:P3buC3tar7571I9gTGyqHQ==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:9lzl6WCwTBSWgpEQ7So=,iv:RbevHpQS8ZNYkraWjhBeQNpjEMB2lvTjLB4MNsZmdo4=,tag:537orrP+2UmirSNs+R+xQQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y8k6aj5un65mwy7t0s6sndrpqevp3hr749facgl3ha8w5dsxqp7s95phh3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1Yi81akxRTFh3cno5djYr
            bVBzODRIL1N4NjdDU0ZqUEZ5Z3VENzJ4SEU0CnNiNEdRRWtlc3hlMVQxcExJbTQ0
            YXFvclFWZkhnSS9uTGhnZkducTdINGsKLS0tIGNhT2d1SjNFTnFBNHJjbE5LMm9j
            OUZiVkF6aEhiNGlVcWZCYjhOdlpmREEKOpzLsycET2/nG83yX6haG6wv4Bl9ieu5
            KfXUdY/X7jy6KGuA+crDUxo3gf3hbj2DTETVKx/VjHGyDCwnqcSHZA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-19T21:58:09Z"
    mac: ENC[AES256_GCM,data:4dtqzpKTl1rdhAC6eK3/pPjW1M26Uj9k6jsuckoS7lSRKI9yR1IpxjjQiqnjNMGZESy5c382dEE2HQvpgNzFcHodNQxlh3oQDiW+Y8sgKsNSFIhzfrSMew7YHMeTtr4/mtDPz6CUzX6nYssYsQmaVxsMxjQBUt1aLQjLbqlW67M=,iv:QFS/kSWJnHz+kXmXksZjPU7MPQqtuSlNKuYa9BKXCNM=,tag:DYpa14MU9JfKnlN4kNN71Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
