kind: Secret
ansible_user: ENC[AES256_GCM,data:JLh6kXL6oPUeRfY=,iv:17s6bu2aimwLY7/Y1XwUJzrVWX0GJ3qojT9yANyZjWg=,tag:XvoOXu0CMcnsjWOpmbkYXg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:tgk1psvzYr8PCskO,iv:O5G2hRypunA0QFbbolaxGjVwVxVosvenkXyMsjjx27I=,tag:3ysnhZADAPCaA6c6xIXC4g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y8k6aj5un65mwy7t0s6sndrpqevp3hr749facgl3ha8w5dsxqp7s95phh3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPUUNMWWQrVjdRZGQydVJh
            ZHE4SHZNdTU1bW1YTHlHdUN3M29yZmdzcURjCmtOV2Fqc2JVcmJncG42WUFDQ0NW
            Zm1CQWt4aW5MVHVacGFhQTQ5WDFSU28KLS0tIDFCbFdxWFo5dTZLNys2TkhsNUxy
            OWhockNyVFdhSU05VHpDTVBoVXBkYUkKki5LZiqtiogejZkgQJItSij0wQXAdvI0
            7DGnRh4hmZ2AdiIJF5BT3S2dFAUFEYqB+B23NOGibsYYaIBgYxHzlQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-19T21:58:09Z"
    mac: ENC[AES256_GCM,data:CWrc/krL9ypqXQ4RJiu8nk6Yc9xgkFdqkra20zepurSb7yUi2JCyxGWL/FM47bf2gqRmDolwOwhMM9HP5EYkeGL8mkKuEBJoXBAOe9L/PEn1i8Od/o4fWFmTrIeoXhZlJ1YR4NBnnjgFVZ+SPQDU5DuZoKkKlhIPy9JDsxu/NeY=,iv:EJX6vSvDufuFPfCXOaeazJvUOb3MWaMy5MmaAeJoyfQ=,tag:JtLgValpOAH6CDE8u7/o0w==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
