kind: Secret
ansible_user: ENC[AES256_GCM,data:xVUym37ptX+B1aE=,iv:sQOmLe5K2SxOzwhsEzeopbX9nAm2aAN8kvHrwggXOlg=,tag:g69Sf9hwQJC+B0yUmxllrw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:0n5R9eP2e1guB2/D,iv:um/WonzDh9NetccgeX3nzzV/GSu/bWWWKUVVZuFIhDk=,tag:vWdegCCd1RTrKlzk/DYqsA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y8k6aj5un65mwy7t0s6sndrpqevp3hr749facgl3ha8w5dsxqp7s95phh3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBeWpacEZLcVEwcSs3blBp
            TmZ1Um4yaWh0N2s2R0FucTROLzZBNUtJZFRBCmdmL3AxSHFSUktlL1ZYSjRvcHZK
            cjRZWENTRHFGRHVLa1dqVVU5Q2hzZG8KLS0tIFRXUjlLY2pJUXNQV3FqMnUyZmp2
            RUVOWG14QllXQXE2dlhiQS82R1FWKzQKM+prj9ZTX5e13yJNclYbA8BndUVml1Xe
            wUQ7nCgUjvpa13PJoC8pswnZVqEEdlRLJX49qkVNy2hzMvmCAKOpxQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-19T21:58:09Z"
    mac: ENC[AES256_GCM,data:VKP6zp8fGC/NGcio19ybljaeIiASpDVQD0BLFdLtydLe7jppaoOdRSjI/W2NaIBNQBZFHBaIByZbsk+uaPmPKw9AYp+FkIB2ky1w1cqVf9lZ7KT+wZlfSiF9CGR8wFGJv+o47CxBzv09tqIkUIiuwGDX510KZ/g+0M35TzjRzrQ=,iv:sTtz8DEXCj8AV0cp+CFaEtZh3FHCsaln8hW16yNVZFU=,tag:Z6aOjP48oxoLGISCRRmQIg==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
