kind: Secret
ansible_user: ENC[AES256_GCM,data:RtFV6BXwfJ5QTjE=,iv:0jvyAuO2Fx9Jgi2ya2YVEMU/+NtNy2PgjjJ3RPXBz0k=,tag:nl0ayKHu3KyQ6uvQW5BkHw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:+sgJHp29jB0fRXG/,iv:AAwVCSFqLbjAnCsPJp0zclWvnlfZ7yG63z+U7p7j1zA=,tag:gsAusqxVVrtfRbmxVWD8nA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y8k6aj5un65mwy7t0s6sndrpqevp3hr749facgl3ha8w5dsxqp7s95phh3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBcVBYMmVxUnZWWERvSG1q
            VVpIZ29KNTdLVFBIUTlvWTJOSWVoSHZMajBVCkZ2M0lja3pMVVkycWpmSDBuU2xJ
            Zm9oNS9HbVhUY0lhZXVSVVlaejM1dlUKLS0tIE1XSTVDeGJjbitvTUVUSmlTSndW
            M0gxdXNRWUZodzdpeUx4TnZFMURkRDAKzgY5tVB6tjxAyoIlWExOF8Twce6bfSA3
            oH/eZtDrS1gcS2UueDHOb887NX/bUcV3h0lMy4fKbpLbU8XYjH2wmg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-19T20:00:44Z"
    mac: ENC[AES256_GCM,data:mM3m5waSVImh/GntneWIpN44dUt9/AOrRCEMQ8I9Cu6vMKp9r2DmWyHrmJj+hLWFmYKVV7WKf6kDpr+mXUC82kN0E1mm64w6uEkYpV33xE0mr9IRKJguXl8cHxIDq/MeoJ9aDEIe5EJQLj2gc/CofDHMomcHKtliQFrJEojALJk=,iv:oHrCeu3n/z4tqQAZ7vRlAKblrxi0YPcWTm5JnGzSK2I=,tag:UpIS67KPkd+Y3bDqSwYoHQ==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
