# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:sqG2IFvPcgI4,iv:Tli2mf5C+jc9z/NniECHHlyzy3Xh8e3gxAd05xvmpbE=,tag:6ecB8lKAqtXf+Szjq7+Ysg==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:Sx+bsD+doax6nAtwe+BjPmp1,iv:VA+x8NHQgWSBHGVwWneDmpqjiMBfqgftebZUhkKxeBw=,tag:nWEorNtdDMa/CRERHDdhNw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y8k6aj5un65mwy7t0s6sndrpqevp3hr749facgl3ha8w5dsxqp7s95phh3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOQWZkRm5xak1mdDd4Nlg1
            NHFLYXF6UVMzQ2ZYUmgyWWdzc1JhQlFmNFVVCk9WcDhRU2lZeng5ZUhzYXZaOUtK
            S1VIcUlrY3ZlQkRiY3M1K2xJejA1bDgKLS0tIC9GQyszRUtyeHZKajhXV0RIK2pp
            VEZIOVNMbmppbmhQMlU1UVJZY0dRZTQKJNtw1fK4QdMTJZBL05dYB/D5tjfVMds7
            EC+x48/M6/nO8TelQ2/8szByq6QfRbA/UmOjvVZv7yGRcsIP66IZLw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-19T20:00:44Z"
    mac: ENC[AES256_GCM,data:dXPGiyr0UO9ngJdGr/iSdGuuMRLsV6KqQUEHSOTOWfGt3rDJh6YfU4C2aKyVUCxJIm3VRJqq1so2YKsAYyDETBl1n7U8+mbym3bWjp6Wj1wU2OsMAOVRVag1c/uOSM2VwgMaWDtED6udzRcdSwUK0+uzBS/O7wL2k+uGQPq5gMo=,iv:iOysQA83Y1/RFfNPW/w7QDPGhBdrA1ixuAKAb+Idz2I=,tag:UoDkByhzZWRoL+xZm2cJzA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
