# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:PYzlCb/A2SUH,iv:YfGM5wNrctitRkuWYqg3PzyrMxMiIurH6Qnmd9+u9vQ=,tag:l/hkd1Ee1QF0gouo+gxu1g==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:F0jBUX0m2OpFTl2Qi6B90zB4,iv:ZldXeLOOLpBy57XzRlwceMm4yqISB3/X37Tn5v/P0QU=,tag:aJ0povZBx4fA2jTE2uzcSA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y8k6aj5un65mwy7t0s6sndrpqevp3hr749facgl3ha8w5dsxqp7s95phh3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQYVJlRUFScXo0bXczbDdr
            NUFqOU0wZjhFQUkzcGVCUDIvRnpRSVlkN2hBCmkwOFB1bkVNL09qSklpYitIa3NE
            QWVCR1VwNFNtbGhnaEFwMGdTNFEzYjAKLS0tIHgybm14dStMcGNiS1hoUDZheE4r
            WGs3YnJNZHRIWnJENTVjVk1nd2Zod0UKKPVFzGQ6YjJ/K7gBMwSdNDCoj1d1YioS
            gNiBU0WB50Bpe7GKl+i87n1xBg8AM2Ngg/2iktBPnEzP5eVMPJyN/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-19T21:58:09Z"
    mac: ENC[AES256_GCM,data:2zQj9wHt6sIzOaKbUixeSLwGUFVOXEn3NjINxB4AyvG0/iDrmm0+p9+n92XqpbqqQ8IHNkWy8czR32+zVgFEPTgKGd0rtkN6Ndh/3JLarSrwlsbOAy1eJowruhXQbc06E15XKgHtAKodkSJ3GbrJMY7vRcy8ACPzw8H2guqQXpE=,iv:F19hao/i4hwPe4BxsSfAQSAuR7vI0/bsaL4iHAvH+BY=,tag:YQG+J1ALc//3EKA1n4Ecxw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
