# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:HXs+c4SFcGir,iv:yYLyo+eT2Y1cAjBxIQzJO4W8CKk5acqM3KWqm3WS6E8=,tag:5lf0VaBdHEiR5Usv4z54ow==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:CO+h1yuQVFcCDHJw8hknF7cR,iv:APT/uNVMbH3h1T5eB5U/gdmeiPJatFyK4114bu07G0A=,tag:9L6wm1zjQB++dfFD7ruLsQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y8k6aj5un65mwy7t0s6sndrpqevp3hr749facgl3ha8w5dsxqp7s95phh3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZSVVnTU1SLzMwKzc5NHNK
            QzRPc2RjQ21ka3VBL0dnT3dId0RUVWs5UDFRCmVjeXFDNTVpQlhMRXV4Q2pJR3E3
            LzBtVklXZFZEYVkwTXkxQy93a1BjamsKLS0tIHpqL0h0WEFKRG1XUUw3YUdKVTJS
            c1dqVXdtRHVJbS9hcFN3SHo5VEI1a1EKDG339YtJ+BqtuyWwXBVBhT7/hb3n9fER
            ldytLQO/8gaeKQ1qkIw2buCGMsiDLNs1RUmSEe3LQayumhxS8p8fGQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-19T19:50:34Z"
    mac: ENC[AES256_GCM,data:qH56HEbcWo2OO4c+LVKs2DTjqvN74vBicmN5sLBGvKWNxf8bVy5jQC1F78yGIdfIMKJ9XLXFv+cUpd4Rl8ERWasEhkiWCk+OVqFASBELSRYb7WVxtu40aQfmFNhgZgZwJThig2GY7KWJ1+Xllw8ve22h/3jqHCWn80VqsVwd+ts=,iv:PX7gjmBz2TdF28ekFS8qFPOi8VqrbNCIA7yWllO3/q8=,tag:VKW7c4LDkpiEGgEeRfrc3A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
